# 사이킷런
scikit-learn은 파이썬용 머신러닝 라이브러리다.

In [1]:
import sklearn
sklearn.__version__

'0.20.1'

# Iris Data

In [2]:
# 데이터 불러오기 및 딕셔너리의 키값 확인

from sklearn.datasets import load_iris

iris_dataset = load_iris()
print("iris_dataset key : {}" .format(iris_dataset.keys()))

iris_dataset key : dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [3]:
# 데이터 확인 및 데이터 형태 보기

print(iris_dataset["data"])
print("shape of data : {}" .format(iris_dataset["data"].shape))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [4]:
# Feature 변수명 확인
print(iris_dataset["feature_names"])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
# Target 확인
print(iris_dataset["target"])
print(iris_dataset["target_names"])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [6]:
# 데이터에 대한 전체적인 요약 정보
print(iris_dataset["DESCR"])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

# 사이킷런을 이용한 데이터 분리

In [7]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_label, test_label = train_test_split(iris_dataset["data"],iris_dataset["target"], test_size = 0.25, random_state = 42)

print("shape of train_input : {}" .format(train_input.shape))
print("shape of train_label : {}" .format(train_label.shape))
print("shape of test_input : {}" .format(test_input.shape))
print("shape of test_label : {}" .format(test_label.shape))

shape of train_input : (112, 4)
shape of train_label : (112,)
shape of test_input : (38, 4)
shape of test_label : (38,)


# 사이킷런을 이용한 지도학습

####  K-nearest neighbor classifier : K-최근접 이웃 분류기
 - 데이터에 대한 가정이 없어 단순하다.
 - 다목적 분류와 회귀에 좋다.
 - 높은 메모리를 요구한다.
 - k값이 커지면 계산이 늦어질 수 있다.
 - 관련 없는 기능의 데이터의 규모에 민감하다.

In [8]:
# K-최근접 이웃 분류기 생성하기
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

# 모델에 훈련 데이터(75%) 적합시키기
knn.fit(train_input, train_label)

# 새로운 데이터 생성
import numpy as np
new_input = np.array([[6.1,2.8,4.7,1.2]])

# 새로운 데이터에 대한 예측값
knn.predict(new_input)

# 테스트 데이터(25%)에 대한 예측값
knn.predict(test_input)

# 예측 정확도
print("test accuracy : {:.2f}" .format(np.mean(knn.predict(test_input) == test_label)))

test accuracy : 1.00


# 사이킷런을 이용한 비지도학습

#### Kmeans Cluster
 - 초기값을 랜덤으로 설정하기 때문에 매번 결과가 바뀔 수 있다.
 - 0번 군집을 "1" 품종으로, 1번 군집을 "0" 품종으로, 2번 군집을 "2" 품종으로 라벨링 하면 된다.

In [9]:
# K-평균 군집화 모델
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters = 3)

# 훈련데이터(75%) 적합시키기
k_means.fit(train_input)

# 적합결과 확인하기
print(k_means.labels_)

print("")

# 잘 예측이 되었는지, 각 군집의 종 확인하기
print("0 Cluster :", train_label[k_means.labels_ == 0])
print("1 Cluster :", train_label[k_means.labels_ == 1])
print("2 Cluster :", train_label[k_means.labels_ == 2])

print("")

# 새로운 데이터 생성하기
import numpy as np
new_input = np.array([[6.1,2.8,4.7,1.2]])

# 새로운 데이터에 대한 예측값
prediction = k_means.predict(new_input)
print("새로운 데이터에 대한 예측값 : ",prediction)

print("")

# 테스트 데이터(25%)에 대한 예측값
predict_cluster = k_means.predict(test_input)
print("테스트 데이터에 대한 예측값 : ",predict_cluster)

print("")

# 각 군집에 알맞는 품종 라벨링하기
np_arr = np.array(predict_cluster)
np_arr[np_arr==0], np_arr[np_arr==1], np_arr[np_arr==2] = 3, 4, 5
np_arr[np_arr==3] = 1
np_arr[np_arr==4] = 0
np_arr[np_arr==5] = 2
predict_label = np_arr.tolist()
print("바뀐 라벨 : ", predict_label)

print("")

# 예측 정확도
print("test accuracy : {:.2f}" .format(np.mean(predict_label == test_label)))

[1 1 2 2 2 1 1 2 2 0 2 0 2 0 2 1 0 2 1 1 1 2 2 1 1 1 2 1 2 0 1 2 2 1 2 2 2
 2 0 2 1 2 0 1 1 2 0 1 2 1 1 2 2 0 2 0 0 2 1 1 2 0 1 1 1 2 0 1 0 0 1 2 2 2
 0 0 1 0 2 0 2 2 2 1 2 2 1 2 0 0 1 2 0 0 1 0 1 0 0 0 2 0 2 2 2 2 1 2 2 1 2
 0]

0 Cluster : [2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2]
1 Cluster : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2 Cluster : [2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 2 1]

새로운 데이터에 대한 예측값 :  [2]

테스트 데이터에 대한 예측값 :  [2 1 0 2 2 1 2 0 2 2 0 1 1 1 1 2 0 2 2 0 1 2 1 0 0 0 0 0 1 1 1 1 2 1 1 2 2
 1]

바뀐 라벨 :  [2, 0, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0, 0, 0, 0, 2, 1, 2, 2, 1, 0, 2, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0]

test accuracy : 0.45


# 사이킷런을 이용한 특징 추출
 - 자연어 처리에서 특징추출이란 텍스트 데이터에서 단어나 문장들을 어떤 특징 값으로 바꿔주는 것을 의미한다.
 - 기존에 문자로 구성되어 있던 데이터를 모델에 적용할 수 있도록 특징을 뽑아 어떤 값으로 수치화한다.
 

#### 특징화 세 가지 방법
 - 1. CountVectorizer
 - 2. TfidVectorizer
 - 3. HashingVectorizer

 - CountVectorizer : 단순히 각 텍스트에서 회수를 기준으로 특징을 추출하는 방법
 - TfidVectorizer : TF-IDF라는 값을 사용해서 텍스트에서 특징을 추출한다.
 - HashingVectorizer : CountVectorizer와 동일한 방법이지만 텍스트를 처리할 때 해시 함수를 사용해서 실행 시간을 현저하게 줄인다.

# CountVectorizer
 - 텍스트 데이터에서 횟수를 기준으로 특징을 추출하는 방법
 - 어떤 단위의 횟수를 셀 것인지는 선택사항이다.
 - 보통은 텍스트에서 단어를 기준으로 횟수를 측정하는데, 문장을 입력으로 받아 단어의 횟수를 측정한 뒤 벡터로 만든다.
 - "나는 배가 고프다"라는 문장을 벡터로 만들었다. 각 단어가 1번 씩 나왔으므로 해당 단어 사전 순서에 맞게 1값을 가진다.
 - 횟수를 사용해서 벡터를 만들기 때문에 직관적이고 간단해서 여러 상황에서 사용할 수 있다는 장점이다
 - 하지만, 단순히 횟수만을 특징으로 잡기 때문에 큰 의미가 없지만 자주 사용되는 단어들, 예를 들면 조사 혹은 지시대명사가 높은 특징값을 가지기 때문에 유의미하게 사용하기 어려울 수 있다.
 - 이러한 문제점을 해결할 수 있는 TF-IDF 방식이 있다.

In [10]:
# CountVectorizer 구현하기

# 연습 데이터 생성하기
from sklearn.feature_extraction.text import CountVectorizer
text_data = ["나는 배가 고프다", "내일 점심 뭐먹지", "내일 공부 해야겠다", "점심 먹고 공부 해야지"]

# 단어 사전 만들기
count_vectorizer = CountVectorizer()
count_vectorizer.fit(text_data)
print(count_vectorizer.vocabulary_)

print("")

# 텍스트 데이터를 벡터로 만들기
sentence = [text_data[0]]
print("나는 배가 고프다")
print(count_vectorizer.transform(sentence).toarray())

{'나는': 2, '배가': 6, '고프다': 0, '내일': 3, '점심': 7, '뭐먹지': 5, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}

나는 배가 고프다
[[1 0 1 0 0 0 1 0 0 0]]


# TfidfVecotorizer
 - TFidVectorizer는 TF-IDF라는 ㅌ특정한 값을 사용해서 텍스트 데이터의 특징을 추출하는 방법이다.
 - 각 값이 의미하는 바를 간단히 설명하면 TF(Term Frequency)란 특정 단어가 하나의 데이터 안에서 등장하는 횟수를 의미한다.
 - 그리고 DF(Document Frequency)는 문서 빈도 값으로, 특정 단어가 여러 데이터에 자주 등장하는지를 알려주는 지표이다.
 - IDF(Inverse Document Frequency)는 이 값에 역수를 취해서 구할 수 있으며, 특정 단어가 다른 데이터에 등장하지 않을수록 값이 커진다.
 - TF-IDF란 이 두 값을 곱해서 사용하므로 어떤 단어가 해당 문서에 자주 등장하지만 다른 문서에는 많이 없는 단어일수록 높은 값을 가지게 된다. 따라서 조사나 지시대명사처럼 자주 등장하는 단어는 TF값은 크지만 IDF값은 작아지므로 CountVectorizer가 가진 문제점을 해결한다.

In [11]:
# TfidfVectorizer 구현하기
from sklearn.feature_extraction.text import TfidfVectorizer
text_data = ["나는 배가 고프다", "내일 점심 뭐먹지", "내일 공부 해야겠다", "점심 먹고 공부 해야지"]

# 단어 사전 구현하기
tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer.fit(text_data)
print(tfidf_vectorizer.vocabulary_)

print("")

# 텍스트 데이터를 벡터로 만들기
sentence = [text_data[3]]
print("점심 먹고 공부해야지")
print(tfidf_vectorizer.transform(sentence).toarray())

# "먹고"와 "해야지"가 조금 더 높은 이유는 다른 데이터에서는 잘 나오지 않는 단어이기 때문이다.

{'나는': 2, '배가': 6, '고프다': 0, '내일': 3, '점심': 7, '뭐먹지': 5, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}

점심 먹고 공부해야지
[[0.         0.43779123 0.         0.         0.55528266 0.
  0.         0.43779123 0.         0.55528266]]


이처럼 특징 추출 방법으로 TF-IDF 값을 사용할 경우, 단순 횟수를 이용하는 것보다 각 단어의 특성을 좀 더 잘 반영할 수 있다.